name: Deploy Production

on:
  release:
    types: [published]

  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Deploy
        run: |
          curl -X POST ${{ secrets.PLOI_PROD_DEPLOY_URL }}
