name: Pint

on:
  push:
    branches:
      - main
    paths:
      - '**.php'
      - '.github/**.yml'
  pull_request:
    paths:
      - '**.php'
      - '.github/**.yml'

jobs:
  pint:
    name: Pint
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          ref: ${{ github.head_ref }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          coverage: none

      - name: Install composer dependencies
        uses: ramsey/composer-install@v3
        with:
          composer-options: "--optimize-autoloader --prefer-dist --no-scripts"

      - name: Run Pint
        run: ./vendor/bin/pint

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Apply Pint style fixes
